# Generated by Django 3.1.7 on 2021-03-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('simbolo', models.SlugField(max_length=100, verbose_name='Símbolo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_historico', models.DateTimeField(verbose_name='Data')),
                ('ultimo', models.FloatField(verbose_name='Último')),
                ('variacao', models.FloatField(verbose_name='Var%')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historicaldata.ativo', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Dado Histórico',
                'verbose_name_plural': 'Dados Históricos',
                'ordering': ['data_historico', 'ativo'],
            },
        ),
    ]
