# Generated by Django 3.1.7 on 2021-03-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_historico', models.DateTimeField(verbose_name='Data')),
                ('ultimo', models.FloatField(verbose_name='Último')),
                ('variacao', models.FloatField(verbose_name='Var%')),
                ('ativo', models.CharField(max_length=100, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Dado Histórico',
                'verbose_name_plural': 'Dados Históricos',
                'ordering': ['data_historico', 'ativo'],
            },
        ),
    ]
