# Generated by Django 3.1.7 on 2021-03-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleverbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='data_historico',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
